<?php
/**
 * Implementation of hook_help().
 */
function birthday_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('Configure birthday module for content profile.');
  }
}

/**
 * Implementation of hook_menu().
 */
function birthday_menu() {
  $items = array();

  $items['admin/settings/birthday'] = array(
    'title' => 'Birthdays',
    'description' => 'Configure birthday block.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('birthday_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function birthday_admin_settings() {
  $types = content_profile_get_types('names');


  $options = array();

  foreach ($types as $type => $name) {
    $result = db_query('SELECT label FROM {content_node_field_instance} WHERE widget_module = "date" AND type_name = "%s"', $type);

    while ($data = db_fetch_object($result)) {
      $options[] = $data->label;
    }
  }

  $form['birthdays_field'] = array(
    '#type' => 'radios',
    '#title' => t('Which field is your birthday field'),
    '#options' => $options,
    '#default_value' => variable_get('birthdays_field', ''),
  );

  return system_settings_form($form);
}
